apiVersion: v1
kind: Pod
metadata:
  labels:
    run: yellow
  name: yellow
spec:
  containers:
  - image: busybox
    name: lemon # container 1
    command:
      - sleep
      - "1000"
  - name: gold # container 2
    image: redis
