apiVersion: v1
kind: Pod

metadata:
  name: myapp-pod
  namespace: dev
  labels:
    app: App1 # copy as selectors to service.yml
    type: front-end

spec:
  containers:
  - name: nginx-container
    image: nginx

  nodeName: node02 # defines the pod to sechdule on the defined node

or another way - create binding 

apiVersion: v1
kind: Binding
metadata:
  name: nginx
target:
  apiVersion: v1
  kind: Node
  name: node02 # to tell the pod to schedule on the defined node (node02)
