# pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-log
spec:
    persistentVolumeReclaimPolicy: Retain
    accessModes: [ "ReadWriteMany" ]
    capacity:
     storage: 100Mi
    hostPath:
     path: /pv/log
     
# pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
   requests:
     storage: 1Gi

# pod with pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: web
  volumes:
    - name: web
      persistentVolumeClaim:
        claimName: myclaim

# pod with pv (no pvc required)
---
apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
  - name: event-simulator
    image: kodekloud/event-simulator
    env: # Optional
    - name: LOG_HANDLERS # Optional
      value: file # Optional
    volumeMounts:
    - mountPath: /log
      name: log-volume

  volumes:
  - name: log-volume
    hostPath:
      path: /var/log/webapp  # directory location on host
      type: Directory # Optional

# https://kubernetes.io/docs/concepts/storage/persistent-volumes/#claims-as-volumes
# https://github.com/kodekloudhub/certified-kubernetes-administrator-course/blob/master/docs/08-Storage/09-Using-PVC-in-PODs.md
