# pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-log
spec:
    persistentVolumeReclaimPolicy: Retain
    accessModes: [ "ReadWriteMany" ]
    capacity:
     storage: 100Mi
    hostPath:
     path: /pv/log
     
# pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes: [ "ReadWriteMany" ]
  storageCLassName: google-storage # only used when pv is not create and SC is created
  resources:
   requests:
     storage: 1Gi

# pod with pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: web
  volumes:
    - name: web
      persistentVolumeClaim: # replaced by `hostPath` from pv
        claimName: myclaim

# pod with pv (no pvc required)
---
apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
  - name: event-simulator
    image: kodekloud/event-simulator
    env: # Optional
    - name: LOG_HANDLERS # Optional
      value: file # Optional
    volumeMounts:
    - mountPath: /log
      name: log-volume
      
  # us the following section of the volume coming from pv
  volumes:
  - name: log-volume
    hostPath:
      path: /var/log/webapp  # directory location on host
      type: Directory # Optional
      
  # use the following section coming from pvc
  volumes:
    - name: web
      persistentVolumeClaim:
        claimName: myclaim

# Storage Class
# Now, we have a Storage Class, So we no longer to define Persistent Volume. It will create automatically when a Storage Class is created. It's called Dynamic Provisioning.
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: google-storage
provisioner: kubernetes.io/gce-pd # no provisioner means - it doesn't support sc
# Silver Class
parameters:
   type: pd-standard
   replication-type: none
# or Gold Class
parameters:
   type: pd-ssd
   replication-type: none
# or Platinum Class
parameters:
   type: pd-ssd # [pd-standard | pd-ssd]
   replication-type: regional-pd # [none | regional-pd]

# SC from GKE & AWS
#https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes#storageclasses
#https://docs.aws.amazon.com/eks/latest/userguide/storage-classes.html

# General
# https://kubernetes.io/docs/concepts/storage/persistent-volumes/#claims-as-volumes
# https://github.com/kodekloudhub/certified-kubernetes-administrator-course/blob/master/docs/08-Storage/09-Using-PVC-in-PODs.md

# Master
# https://github.com/kodekloudhub/certified-kubernetes-administrator-course/blob/master/docs/08-Storage/12-Storage-Class.md
