apiVersion: apps/v1
kind: ReplicaSet
metadata: 
 name: myapp-replicaset # ReplicaSet
 namespace: dev
 labels: # labels of the ReplicaSet itself
  app: app
  type: front-end
  
spec: 
 replicas: 3
 selector:
  matchLabels:
   app: App1
   
# inorder for replicaSet to configure with pod -> SELECTOR for replicaSet(above) MUST MATCH label for pod (BELOW)

template: # - Pod
 metadata: 
  name: app1-pod
  labels: # labels defined in template section are labels configured in pod
    app: App1
    type: front-end
    
spec:
 containers:
  - name: nginx
    image: nginx
    # - name : backend-container # additional item
    #    image: redis
